"use client";
import {useEffect,useState} from "react";

type Student={id:string;student_name:string;class_name:string;section:string};
type Ticket={ticket_id:string;subject_name:string;reason:string;status:string;created_at:string};

export default function Parent(){
  const [students,setStudents]=useState<Student[]>([]);const [studentId,setStudentId]=useState("");const [reason,setReason]=useState("");const [tickets,setTickets]=useState<Ticket[]>([]);const [result,setResult]=useState("");const [error,setError]=useState("");
  async function load(){const [s,t]=await Promise.all([fetch("/api/parent/students"),fetch("/api/parent/early-pickup")]);const sd=await s.json();const td=await t.json();if(s.ok){setStudents(sd.students||[]);setStudentId(current=>current||sd.students?.[0]?.id||"")}if(t.ok)setTickets(td.tickets||[]);}
  useEffect(()=>{void load()},[]);
  async function submit(){setResult("");setError("");const r=await fetch("/api/parent/early-pickup",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({studentId,reason})});const d=await r.json();if(!r.ok){setError(d.error||"Request failed");return}setResult(`Request ${d.ticket.ticket_id} submitted for approval.`);setReason("");void load();}
  return <main style={{maxWidth:760,margin:"auto",padding:24}}><p style={{color:"#2563eb",fontWeight:700}}>PARENT PORTAL</p><h1>Request Early Pickup</h1><p style={{color:"#687386"}}>Submit a request for a linked child. The school approver will receive the reason and request details.</p><section style={{background:"white",padding:22,borderRadius:14}}><label>Student<select value={studentId} onChange={e=>setStudentId(e.target.value)} style={{display:"block",width:"100%",padding:14,marginTop:7}}>{students.map(s=><option key={s.id} value={s.id}>{s.student_name} · Class {s.class_name}{s.section}</option>)}</select></label><label style={{display:"block",marginTop:16}}>Reason<textarea value={reason} onChange={e=>setReason(e.target.value)} placeholder="Example: Medical appointment" style={{display:"block",width:"100%",height:100,padding:12,marginTop:7,boxSizing:"border-box"}}/></label><button onClick={()=>void submit()} disabled={!studentId||!reason.trim()} style={{width:"100%",marginTop:20,padding:15,border:0,borderRadius:10,background:"#2563eb",color:"white"}}>Submit for Approval</button>{result&&<p style={{color:"#15803d",fontWeight:700}}>{result}</p>}{error&&<p style={{color:"#dc2626",fontWeight:700}}>{error}</p>}</section><h2 style={{marginTop:28}}>My Requests</h2>{tickets.map(t=><article key={t.ticket_id} style={{background:"white",padding:18,borderRadius:12,marginTop:10}}><b>{t.subject_name}</b><p style={{margin:"8px 0"}}>Reason: {t.reason}</p><p style={{margin:0}}><b>Status:</b> {t.status}</p>{t.status==="QR_READY"&&<p style={{color:"#15803d",fontWeight:700}}>QR approved and ready for reception.</p>}{t.status==="REJECTED"&&<p style={{color:"#dc2626",fontWeight:700}}>Request rejected by the approver.</p>}</article>)}</main>
}
