"use client";
import {useEffect,useState} from "react";

type Request={id:string;ticket_id:string;subject_name:string;reason:string;status:string;parent_name:string;parent_mobile:string;created_at:string};
export default function Approvals(){
 const [requests,setRequests]=useState<Request[]>([]);const [error,setError]=useState("");const [busy,setBusy]=useState("");const [message,setMessage]=useState("");
 async function load(){const r=await fetch("/api/approvals");const d=await r.json();if(!r.ok){setError(d.error||"Unable to load approvals");return}setRequests(d.requests||[])}
 useEffect(()=>{void load()},[]);
 async function act(ticketId:string,action:string){setBusy(ticketId);setMessage("");const r=await fetch("/api/approvals",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({ticketId,action})});const d=await r.json();setBusy("");if(!r.ok){setError(d.error||"Action failed");return}setMessage(action==="APPROVE"?`Approved. QR generated for ${ticketId}.`:`Rejected ${ticketId}. Parent, admin, reception and security have been notified.`);void load();}
 return <main style={{maxWidth:900,margin:"auto",padding:24}}><h1>Pending Approvals</h1><p style={{color:"#687386"}}>Every request shows the parent's actual reason before approval.</p>{message&&<p style={{color:"#15803d",fontWeight:700}}>{message}</p>}{error&&<p style={{color:"#dc2626",fontWeight:700}}>{error}</p>}{!requests.length&&!error&&<p>No pending approvals.</p>}{requests.map(r=><article key={r.id} style={{background:"white",padding:22,borderRadius:14,marginTop:14}}><b>Early Pickup Request</b><h2 style={{margin:"8px 0"}}>{r.subject_name}</h2><p>Parent: {r.parent_name||"—"} {r.parent_mobile&&`· ${r.parent_mobile}`}</p><p><b>Reason:</b> {r.reason}</p><p><b>Submitted:</b> {new Date(r.created_at).toLocaleString()}</p><button disabled={busy===r.ticket_id} onClick={()=>void act(r.ticket_id,"APPROVE")} style={{padding:"10px 18px",background:"#16a34a",color:"white",border:0,borderRadius:8}}>Approve & Generate QR</button>{" "}<button disabled={busy===r.ticket_id} onClick={()=>void act(r.ticket_id,"REJECT")} style={{padding:"10px 18px",border:0,borderRadius:8}}>Reject</button><hr/><small>Workflow: Approver → Reception → Security → Closed</small></article>)}</main>
}
