"use client";
import {useEffect,useState} from "react";

const types=["SCHOOL","HOSPITAL","APARTMENT","CORPORATE","OTHER"];
const moduleOptions=["USER_MANAGEMENT","MASTER_DATA_IMPORT","VISITOR_MANAGEMENT","EARLY_PICKUP","QR_VERIFICATION","RECEPTION","SECURITY","VEHICLE_MANAGEMENT","PATROL","EMERGENCY_HELP","REPORTS","NOTIFICATIONS"];

type Tenant={id:string;code:string;name:string;type:string;status:string;contact_name:string;contact_mobile:string;modules:string[]};
export default function PlatformAdmin(){
 const [tenants,setTenants]=useState<Tenant[]>([]);const [form,setForm]=useState({name:"",code:"",type:"SCHOOL",address:"",contactName:"",contactMobile:"",contactEmail:"",adminName:"",adminUsername:"",adminMobile:"",adminPassword:""});const [modules,setModules]=useState<string[]>(moduleOptions);const [message,setMessage]=useState("");const [error,setError]=useState("");
 async function load(){const r=await fetch("/api/platform/tenants");const d=await r.json();if(r.ok)setTenants(d.tenants||[]);else setError(d.error||"Unable to load tenants")}
 useEffect(()=>{void load()},[]);
 function set(k:keyof typeof form,v:string){setForm(x=>({...x,[k]:v}))}
 async function create(){setMessage("");setError("");const r=await fetch("/api/platform/tenants",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...form,modules})});const d=await r.json();if(!r.ok){setError(d.error||"Tenant creation failed");return}setMessage(`Tenant ${d.tenant.code} created. Tenant Admin username: ${d.user.username}`);setForm({name:"",code:"",type:"SCHOOL",address:"",contactName:"",contactMobile:"",contactEmail:"",adminName:"",adminUsername:"",adminMobile:"",adminPassword:""});void load()}
 const field=(label:keyof typeof form,text:string,type="text")=><label style={{display:"block",marginTop:12}}>{text}<input type={type} value={form[label]} onChange={e=>set(label,e.target.value)} style={{display:"block",width:"100%",boxSizing:"border-box",padding:11,marginTop:5,border:"1px solid #d7dce5",borderRadius:8}}/></label>;
 return <main style={{maxWidth:1100,margin:"auto",padding:24}}><p style={{color:"#2563eb",fontWeight:700}}>SMARTCHECK PLATFORM ADMIN</p><h1>Tenant Management</h1><p style={{color:"#687386"}}>Create and provision schools, hospitals, apartments and other providers. Each tenant gets an isolated workspace and its own administrator.</p>{message&&<p style={{color:"#15803d",fontWeight:700}}>{message}</p>}{error&&<p style={{color:"#dc2626",fontWeight:700}}>{error}</p>}<section style={{background:"white",padding:24,borderRadius:14}}><h2>Create Tenant</h2><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(280px,1fr))",gap:"0 20px"}}>{field("name","Organisation name")}{field("code","Tenant code")}<label style={{display:"block",marginTop:12}}>Organisation type<select value={form.type} onChange={e=>set("type",e.target.value)} style={{display:"block",width:"100%",padding:11,marginTop:5}}>{types.map(t=><option key={t}>{t}</option>)}</select></label>{field("address","Address")}{field("contactName","Contact person")}{field("contactMobile","Contact mobile")}{field("contactEmail","Contact email","email")}</div><h3 style={{marginTop:24}}>Tenant Admin credentials</h3><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(280px,1fr))",gap:"0 20px"}}>{field("adminName","Admin name")}{field("adminUsername","Admin username")}{field("adminMobile","Admin mobile")}{field("adminPassword","Initial password","password")}</div><h3 style={{marginTop:24}}>Enabled modules</h3><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(220px,1fr))",gap:8}}>{moduleOptions.map(m=><label key={m}><input type="checkbox" checked={modules.includes(m)} onChange={e=>setModules(x=>e.target.checked?[...x,m]:x.filter(v=>v!==m))}/> {m.replaceAll("_"," ")}</label>)}</div><button onClick={()=>void create()} style={{marginTop:24,padding:"13px 20px",border:0,borderRadius:9,background:"#2563eb",color:"white",fontWeight:700}}>Create Tenant & Admin</button></section><h2 style={{marginTop:30}}>Tenants</h2>{tenants.map(t=><article key={t.id} style={{background:"white",padding:18,borderRadius:12,marginTop:10}}><b>{t.name}</b> · {t.type} · {t.code}<div style={{color:"#687386",marginTop:6}}>Status: {t.status} · Contact: {t.contact_name||"—"} {t.contact_mobile&&`· ${t.contact_mobile}`}</div></article>)}</main>
}
