"use client";
import {useEffect,useState} from "react";
import Link from "next/link";
const actions={
 PLATFORM_ADMIN:[["Platform Admin","Create and manage tenants","/platform-admin"]],
 ADMIN:[["School Control Center","Manage users, permissions, master data and workflows","/admin"],["Daily Reports","Review operational reports","/reports"]],
 PARENT:[["Early Pickup","Create an early pickup request","/parent"]],VISITOR:[["Visitor Entry","Create a visitor request","/visitor"]],APPROVER:[["Approvals","Review and approve pending requests","/approvals"]],RECEPTION:[["Reception Queue","Verify approved arrivals","/reception"]],SECURITY:[["QR Scanner","Verify reception and security checkpoints","/security/scan"],["Vehicles","Capture and review vehicle entries","/security/vehicles"],["Patrols","Manage patrol checkpoints","/patrols"]]
} as const;
type Role=keyof typeof actions;
export default function Dashboard(){const [role,setRole]=useState<Role|null>(null);const [name,setName]=useState("");useEffect(()=>{fetch("/api/auth/session").then(r=>r.ok?r.json():null).then(d=>{if(d?.user){setRole(d.user.role);setName(d.user.name||"")}}).catch(()=>{})},[]);const links=role?actions[role]:[];async function logout(){await fetch("/api/auth/logout",{method:"POST"});window.location.href="/login"}return <main style={{maxWidth:760,margin:"auto",padding:20,paddingBottom:90}}><header style={{display:"flex",justifyContent:"space-between",alignItems:"flex-start",gap:16}}><div><p style={{color:"#2563eb",fontWeight:700,letterSpacing:.5}}>SMARTCHECK</p><h1>Welcome{name?`, ${name}`:""}</h1><p style={{color:"#687386"}}>Your security workflow dashboard</p>{role&&<span style={{display:"inline-block",padding:"6px 10px",borderRadius:999,background:"#eef4ff",color:"#2563eb",fontSize:12,fontWeight:700}}>{role}</span>}</div><button onClick={()=>void logout()} style={{padding:"9px 12px",border:"1px solid #d7dce5",borderRadius:9,background:"white"}}>Sign out</button></header>{links.length>0&&<><h2 style={{marginTop:28}}>Quick actions</h2><section style={{display:"grid",gap:12,marginTop:12}}>{links.map(([title,description,href])=><Link href={href} key={href} style={{background:"white",padding:18,borderRadius:14,textDecoration:"none",color:"inherit",border:"1px solid #edf0f5"}}><b>{title}</b><p style={{margin:"8px 0 0",color:"#687386"}}>{description}</p></Link>)}</section></>}<nav style={{position:"fixed",bottom:0,left:0,right:0,background:"white",padding:16,textAlign:"center",borderTop:"1px solid #eee"}}>Home &nbsp; · &nbsp; Tasks &nbsp; · &nbsp; Scan &nbsp; · &nbsp; More</nav></main>}
